spring:
  application:
    name: telegram-otp-ms
application:
  telegram:
    token: '7451571902:AAEn-9FxhZjw6ydt5mQS7QIjRmQlYGx4Vcg'
    url: 'https://api.telegram.org'
    exposed-url: 'https://anorbank.uz'
    allowed-updates:
      - 'message'
    max-connections: 40
    enable-set-webhook-on-startup: true
    telegram-bot-username: 'ob_otp_test_bot'